version: '3.8'

services:
  mysql:
    image: mysql
    ports:
      - "3307:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql12345
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=mysql12345
      - MYSQL_DATABASE=picpaydb

    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: